### ISSUE TITLE
New condition for errors.py

### ISSUE THREAD

**Issue by dhill-usgs** [USGS-EROS/espa-web#7]
This error should be caught and handled appropriately in errors.py.

2015-08-07 13:59:35.331 11112 ERROR    ondemand_mapper.py:92:set_product_error -- Exception encountered and follows
Traceback (most recent call last):
  File "/data/espa/mapred/local/taskTracker/espa/jobcache/job_201508030948_0860/attempt_201508030948_0860_m_000121_0/work/./ondemand_mapper.py", line 80, in set_product_error
    logged_contents)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/local/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by dhill-usgs** [comment]
This has a test case generated for it in ordering/tests/test_errors.py and it passes.  It's on the django-1.7-upgrade branch.
